name: Riposte CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Java 17 beállítása
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: CMake, GCC és RPM beállítása (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install build-essential cmake rpm

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Sima fordítás (Minden push esetén)
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: gradle compileKotlinDesktop

      - name: Telepítők generálása (KMP)
        if: startsWith(github.ref, 'refs/tags/v')
        run: gradle packageDistributionForCurrentOS

      - name: Fájlok feltöltése a Release-be
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/compose/binaries/main/*/*.msi
            app/build/compose/binaries/main/*/*.exe
            app/build/compose/binaries/main/*/*.deb
            app/build/compose/binaries/main/*/*.rpm
